services:
  backend:
    image: parkjeonghun/project-backend:latest
    container_name: project-backend
    restart: always
    expose:
      - "8000" # 밖으로는 안 뚫고 도커 내부망에서만 8000번을 엶

  nginx:
    # Nginx는 도커 허브에서 공식 기성품을 바로 땡겨옴
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80" # 진짜 외부로 뚫리는 건 Nginx의 80번 포트뿐임
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 아까 만든 설정 파일을 컨테이너 안으로 밀어 넣음
    depends_on:
      - backend # 백엔드가 먼저 켜진 다음에 Nginx가 켜지게 순서 조절
