services:
  backend-green:
    image: ${DOCKER_USERNAME}/project-backend:latest
    container_name: backend-green
    restart: always
    env_file: .env
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8001
    expose:
      - "8001"
    networks:
      - infra_network

networks:
  infra_network:
    external: true
