services:
  # 1. 수문장 Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # 아까 만든 변수 파일도 Nginx가 읽을 수 있게 볼륨 연결! (경로 주의)
      - ./nginx/service-url.inc:/etc/nginx/conf.d/service-url.inc

  # 2. 메인 DB MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    expose:
      - "3306"
    volumes:
      - ./db_data/mysql:/var/lib/mysql

  # 3. 인메모리 캐시 Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./db_data/redis:/data
