version: "3.8"

services:
  backend:
    image: ${DOCKER_USERNAME}/project-backend:latest
    container_name: project-backend
    restart: always
    expose:
      - "8000"
    depends_on:
      - mysql
      - redis
    env_file: .env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  # 1. 메인 관계형 DB (MySQL)
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - "3306"
    volumes:
      - ./db_data/mysql:/var/lib/mysql
    env_file: .env

  # 2. 인메모리 캐시 (Redis)
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./db_data/redis:/data
