events {}

http {
    # 1. 업스트림 정의 (이름은 고정, 주소는 변수 처리 안 함)
    upstream backend {
        # 초기값은 아무거나 (어차피 아래서 include로 갈아끼울 거임)
        server backend-blue:8000;
        include /etc/nginx/conf.d/service-url.inc;
    }

    server {
        listen 80;
        location / {
            # 2. 업스트림 이름을 직접 찌름 (변수 안 씀!)
            proxy_pass http://backend;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}